spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ticketing
    username: ticketing
    password: ticketing
    driver-class-name: org.postgresql.Driver

  spring:
    jpa:
      hibernate:
        ddl-auto: validate
      defer-datasource-initialization: false


  flyway:
    enabled: true
    locations: classpath:db/migration
